name: telegram notification
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} ha creado un nuevo commit:
            Mensaje del commit: ${{ github.event.commits[0].message }}
            
            Repositorio: ${{ github.repository }}
            
            Puedes revisar los cambios: https://github.com/${{ github.repository }}/commit/${{github.sha}}
